apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-postgres-configmap
data:
  setup-db.sql: |
      CREATE TABLE IF NOT EXISTS author
      (
        id BIGSERIAL PRIMARY KEY,
        name     VARCHAR(200) NOT NULL
      );
      CREATE TABLE IF NOT EXISTS book
      (
        id       BIGSERIAL PRIMARY KEY,
        isbn     VARCHAR(50) NOT NULL,
        title    VARCHAR(500) NOT NULL,
        modified TIMESTAMP WITH TIME ZONE NOT NULL,
        authorId BIGSERIAL NOT NULL REFERENCES author (id)
      );
  postgresql.conf: |
    listen_addresses = '*'
    wal_level = replica
    archive_mode = on
    archive_command = 'test ! -f /database_archive/%f && cp %p /database_archive/%f'
    archive_timeout = 60
